### ISSUE TITLE
License mismatch - GPL vs MIT

### ISSUE THREAD

**Issue by krisgesling** [beasteers/tflit#2]
Hi there,

I just noticed that the `LICENSE` file in the repo (GPL v3.0) differs from the license metadata you have listed in `setup.py` and hence what's shown on PyPI (MIT).

Thought you'd want to know.

Also keen to hear if you find any better way to use pip flags in `setup.py`. Currently I'm [extending the setuptools install cmdclass](https://github.com/MycroftAI/plugin-wake-word-precise/blob/e7703674a111c5f08210d41807ab2b1adeb89f52/setup.py#L24) but there must be a better way...

**Comment by beasteers** [comment]
Ah nice thanks for letting me know! I'll fix that when I get a minute.

You know, honestly I don't get why they can't just push to pypi. It's so aggravating because it takes literally 10 seconds like once you have your wheels you just do `twine upload dist/*` like aghhhh!!!!!! 

At least now they have that google coral index, because when I first wrote this, you had to get all of the distribution/architecture/python version of the current machine to point to the right wheel URL. Meaning that the way I'm doing it is probably not the best, and your up to date way looks much cleaner. I just know that there are considerations around whether you use a wheel or source distribution that I've had trouble getting right when running custom commands and extra installs through setup.py.

Honestly, I considered just pushing tflite-runtime up to pypi under a different name, but I didn't feel confident enough about modifying the pre-built wheel files (I didn't want to miss something and accidentally take over the tflite-runtime name on pypi)

**Comment by JarbasAl** [comment]
I have been using `tflit` under the impression it was MIT, if it is GPL i will need to stop using it. Looking forward to the outcome of this issue

**Comment by beasteers** [comment]
I just fixed the file to say MIT as well. I don't have a strong feeling either way, it was honestly probably just a mistake when copying the repo from another. Hope this helps!
